#!/bin/bash
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
DEST_DIR=
if [ -n "$1" ]
  then
    DEST_DIR=$1
    mkdir $DEST_DIR
fi
CGO_ENABLED=0 GOOS=linux go build -a -x -tags netgo -ldflags "-X main.AppVersion=`git describe --tags`" -o $PROJECT_DIR/$DEST_DIR/bin/swift-consometer .
